### ISSUE TITLE
Windows support for distributed slice

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/linkme#2]

**Comment by lfairy** [comment]
From the linked articles, I can find two issues that may make things difficult:

* Section names must be 8 characters or less. Since 2 characters are taken up by the sorting marker, this leaves us only 6 characters for the unique identifier 😥

* Sections may be padded with zeroes at the beginning *and* end. So we'll need to either restrict ourselves to `NonZero` types or add a tag to each entry.

**Comment by dtolnay** [comment]
Implemented in #4, published in 0.1.2.

**Comment by oberrich** [comment]
Found some more context for the padding issue on Windows:
- [Using linker segments and __declspec(allocate(…)) to arrange data in a specific order](https://devblogs.microsoft.com/oldnewthing/20181107-00/?p=100155)
- [Gotchas when using linker sections to arrange data, part 1](https://devblogs.microsoft.com/oldnewthing/20181108-00/?p=100165)
- [Gotchas when using linker sections to arrange data, part 2](https://devblogs.microsoft.com/oldnewthing/20181109-00/?p=100175)

> [...] it fails to take into account another detail of linker sections: intra-section padding.
> 
> The linker will add padding after a fragment in order to satisfy any alignment requirements of the subsequent fragment. That’s expected.
> 
> What most people aren’t aware of is that the linker is **permitted but not required** to add **padding** after each fragment, **up to the section’s alignment**. In practice, you are likely to see this “unnecessary” padding when using [incremental linking](https://docs.microsoft.com/en-us/cpp/build/reference/incremental-link-incrementally).
> 
> In all cases, the padding **bytes** (if any) **will be zero**.

![image](https://github.com/user-attachments/assets/677cae5e-a972-4424-9def-a16ac8875823)

Seems like this is mostly triggered when using incremental linking, could this be an issue for Rust?
